export default {
  GAME_CHANGE_SCENE: 'GAME_CHANGE_SCENE',
  GAME_COUNTDOWN: 'GAME_COUNTDOWN',
  LANGUAGE_CHANGE: 'LANGUAGE_CHANGE',
  LISTEN_MOUSE_EVENTS: 'LISTEN_MOUSE_EVENTS',
  LOBBY_INTERRUPT: 'LOBBY_INTERRUPT',
  TOGGLE_MUSIC_LOOP: 'TOGGLE_MUSIC_LOOP'
}
