export default {
  CLIENT_CONNECTION: 'CLIENT_CONNECTION',
  CLIENT_LOBBY_START: 'CLIENT_LOBBY_START',
  CLIENT_SCENE_MOVEMENT: 'CLIENT_SCENE_MOVEMENT',
  CLIENT_SPACE_SCENE_MOVEMENT: 'CLIENT_SPACE_SCENE_MOVEMENT',
  CLIENT_WIN: 'CLIENT_WIN',
  SERVER_CONNECTION: 'SERVER_CONNECTION',
  SERVER_COUNTDOWN: 'SERVER_COUNTDOWN',
  SERVER_GAME_START: 'SERVER_GAME_START',
  SERVER_GAME_WAIT: 'SERVER_GAME_WAIT',
  SERVER_LOBBY_COLLAPSE: 'SERVER_LOBBY_COLLAPSE',
  SERVER_LOBBY_END: 'SERVER_LOBBY_END',
  SERVER_LOBBY_INTERRUPT: 'SERVER_LOBBY_INTERRUPT',
  SERVER_SCENE_MOVEMENT: 'SERVER_SCENE_MOVEMENT',
  SERVER_SPACE_SCENE_MOVEMENT: 'SERVER_SPACE_SCENE_MOVEMENT'
}
