package constants

const (
	PacketClientConnection                  = "CLIENT_CONNECTION"
	PacketClientFocus                       = "CLIENT_FOCUS"
	PacketClientLobbyStart                  = "CLIENT_LOBBY_START"
	PacketClientSceneBrawlBombHit           = "CLIENT_SCENE_BRAWL_BOMB_HIT"
	PacketClientSceneBrawlDodge             = "CLIENT_SCENE_BRAWL_DODGE"
	PacketClientSceneBrawlPunch             = "CLIENT_SCENE_BRAWL_PUNCH"
	PacketClientSceneFloatingIslandsCollide = "CLIENT_SCENE_FLOATING_ISLANDS_COLLIDE"
	PacketClientSceneFloatingIslandsFall    = "CLIENT_SCENE_FLOATING_ISLANDS_FALL"
	PacketClientSceneHotPotatoTag           = "CLIENT_SCENE_HOT_POTATO_TAG"
	PacketClientSceneMovement               = "CLIENT_SCENE_MOVEMENT"
	PacketClientSceneStarWarsCollect        = "CLIENT_SCENE_STAR_WARS_COLLECT"
	PacketClientWin                         = "CLIENT_WIN"
	PacketServerConnection                  = "SERVER_CONNECTION"
	PacketServerCountdown                   = "SERVER_COUNTDOWN"
	PacketServerGameStart                   = "SERVER_GAME_START"
	PacketServerGameWait                    = "SERVER_GAME_WAIT"
	PacketServerLobbyCollapse               = "SERVER_LOBBY_COLLAPSE"
	PacketServerLobbyEnd                    = "SERVER_LOBBY_END"
	PacketServerLobbyInterrupt              = "SERVER_LOBBY_INTERRUPT"
	PacketServerSceneData                   = "SERVER_SCENE_DATA"
	PacketServerSceneMovement               = "SERVER_SCENE_MOVEMENT"
)
